name: GCN_partitioning
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - ConfigArgParse=1.1  # 1.0
  - numpy=1.21.5  # 1.18.1
  - PyYAML==5.3
  - scipy==1.4.1
  - torch==1.4.0
  - tqdm==4.42.1
